<?php

namespace Rahmanramsi\LivewirePageGroup\Support;

use Livewire\Livewire;

class LivewireCompatibility
{
    /**
     * @param  class-string  $component
     */
    public function componentName(string $component): string
    {
        // Preserve the aliases generated by Livewire 3 after its registry was removed in Livewire 4.
        $namespace = str_replace(
            ['/', '\\'],
            '.',
            trim(trim((string) config('livewire.class_namespace', 'App\\Livewire')), '\\'),
        );
        $class = str_replace(
            ['/', '\\'],
            '.',
            trim(trim($component, '/'), '\\'),
        );

        $namespace = collect(explode('.', $namespace))
            ->map(fn (string $segment): string => (string) str($segment)->kebab())
            ->implode('.');
        $fullName = str(collect(explode('.', $class))
            ->map(fn (string $segment): string => (string) str($segment)->kebab())
            ->implode('.'));

        if ($fullName->startsWith('.')) {
            $fullName = $fullName->substr(1);
        }

        if ($fullName->endsWith('.index')) {
            $fullName = $fullName->replaceLast('.index', '');
        }

        if ($namespace !== '' && $fullName->startsWith($namespace)) {
            return (string) $fullName->substr(strlen($namespace) + 1);
        }

        return (string) $fullName;
    }

    /**
     * @param  class-string  $component
     */
    public function registerComponent(string $component): void
    {
        $name = $this->componentName($component);
        $manager = Livewire::getFacadeRoot();

        if (is_object($manager) && method_exists($manager, 'addComponent')) {
            Livewire::addComponent($name, null, $component);

            return;
        }

        Livewire::component($name, $component);
    }
}
